version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  worker:
    build: .
    command: ["celery", "-A", "src.tasks.celery_app", "worker", "--loglevel=info"]
    depends_on:
      - redis
    restart: always
